name: Erwin de Haan's Blog
description: Ramblings, mostly
meta_description: "Erwin de Haan's Blog, Ramblings, mostly"

permalink: :year/:month/:title.html
markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: 'https://erwindehaan.com'
google_analytics: 'UA-5639573-12'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'https://erwindehaan.com/'
author:         'Erwin de Haan'
