name: Erwin de Haan's Blog
description: Ramblings, mostly
meta_description: "Erwin de Haan's Blog, Ramblings, mostly"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: 'http://erwindehaan.com'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'http://erwindehaan.com/'
author:         'Erwin de Haan'
